class Constant:
    INDEX_PAGE = "http://automationpractice.com/index.php"
    MY_ACCOUNT_PAGE_TITLE = "MY ACCOUNT"
    WELCOME_MESSAGE = "Welcome to your account. Here you can manage all of your personal information and orders."
    SHOPPING_CART_HEADING = "Your shopping cart"
    ADDRESS_PAGE_TITLE = "ADDRESSES"
    SHIPPING_PAGE_TITLE = "SHIPPING"
    PAYMENT_METHOD_PAGE_TITLE = "PLEASE CHOOSE YOUR PAYMENT METHOD"
    PAYMENT_PAGE_TITLE = "Bank-wire payment."
    ORDER_CONFIRMATION_PAGE_TITLE = "Order confirmation"
    ORDER_CONFIRMATION_TEXT = "Your order on My Store is complete."
